### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by aldnav** [ephraimeg/alive-project#4]
Requirements specification:

- [x] User should be able to view own profile page (displaying basic information)
- [x] From the profile page, user should be able to see appeals he requested (open appeals, done appeals)
- [x] From the profile page, user should be able to see appeals that the user offered to help

**Comment by allenazamoras** [comment]
Allena
- Register
- Login
- Profile Page
- Open appeals
- Closed appeals
- Appeals the users offered to help

**Comment by boredchinese** [comment]
- [x] Layout the Profile Page
- [x] Functionality (with static data)
- [ ] Backend integration

**Comment by ephraimeg** [comment]
@boredchinese 
`Closed appeals` are those that are either deleted or completed while 
`Open appeals` are those that are yet to be addressed or is currently being addressed
there can only be one `active` appeal at a time
